---
abstract: "print your distribution's prerequisites"
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-App-Command-prereqs
provides:
  Dist::Zilla::App::Command::prereqs:
    file: lib/Dist/Zilla/App/Command/prereqs.pm
    version: 1.100750
requires:
  Capture::Tiny: 0
  Carp: 0
  Dist::Zilla::App: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose::Autobox: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-App-Command-prereqs
  homepage: http://search.cpan.org/dist/Dist-Zilla-App-Command-prereqs/
  repository: http://github.com/hanekomu/Dist-Zilla-App-Command-prereqs
version: 1.100750
